# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SapoTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'IQKeyboardManagerSwift'
	pod 'Alamofire', '~> 4.9'
  # Pods for SapoTest

  target 'SapoTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SapoTestUITests' do
    # Pods for testing
  end

end
